# Generated by Django 3.2.7 on 2022-08-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.user')),
            ],
        ),
    ]
