# Generated by Django 3.2.7 on 2022-08-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=200)),
                ('port', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
