# Generated by Django 3.2.7 on 2022-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_smtp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gonderici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.DecimalField(decimal_places=2, max_digits=8)),
                ('host', models.EmailField(max_length=254)),
                ('smtpsecure', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='SMTP',
        ),
        migrations.RemoveField(
            model_name='message',
            name='User',
        ),
    ]
