# Generated by Django 3.2.7 on 2022-08-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220805_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('see', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gonderici',
            new_name='Smmtp',
        ),
        migrations.AddField(
            model_name='message',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.user'),
        ),
    ]
