# Generated by Django 3.2.7 on 2022-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20220805_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('see', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='imageUrl',
            field=models.CharField(max_length=50, null=True, verbose_name='Resim Url'),
        ),
        migrations.AddField(
            model_name='information',
            name='subtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='information',
            name='informate',
            field=models.CharField(max_length=200, verbose_name='Bilgi'),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
    ]
