# Generated by Django 3.2.7 on 2022-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20220817_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Bilgi', 'verbose_name_plural': 'Bilgiler'},
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='user',
            name='imageUrl',
            field=models.CharField(max_length=50, null=True, verbose_name='Resim Url'),
        ),
    ]
