# Generated by Django 3.2.7 on 2022-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20220817_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='smmtp',
            options={'verbose_name': 'SMTP', 'verbose_name_plural': 'SMTP Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Kişi', 'verbose_name_plural': 'Kişiler'},
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=200, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Soyad'),
        ),
    ]
