# Generated by Django 3.2.7 on 2022-08-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20220817_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
            ],
            options={
                'verbose_name': 'İp Adres',
                'verbose_name_plural': 'İp Adresler',
            },
        ),
        migrations.AlterField(
            model_name='information',
            name='informate',
            field=models.CharField(max_length=5000, verbose_name='Bilgi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=2500, verbose_name='İçerik'),
        ),
    ]
