# Generated by Django 3.2.7 on 2022-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20220818_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='User',
        ),
        migrations.AddField(
            model_name='message',
            name='Users',
            field=models.ManyToManyField(to='movies.User'),
        ),
    ]
