# Generated by Django 3.2.7 on 2022-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20220820_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='smmtp',
            name='host',
            field=models.CharField(max_length=200),
        ),
    ]
