# Generated by Django 3.2.7 on 2022-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20220823_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageUrl',
        ),
        migrations.AlterField(
            model_name='information',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Resim Url'),
        ),
        migrations.AlterField(
            model_name='smmtp',
            name='port',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
