# Generated by Django 3.2.7 on 2022-08-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20220823_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='users',
            new_name='Users',
        ),
        migrations.AlterField(
            model_name='information',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Resim Url'),
        ),
    ]
